### ISSUE TITLE
Cyrillic encoding

### ISSUE THREAD

**Issue by victorsmart** [dEajL3kA/tee-win32#2]
Hi!

Sorry for my English. I write with the help of an online translator.

Thank you for tee-for-windows, but i have some troble with use it. The problem is in the Cyrillic encoding. 
example 1: CMD - OK, TXT file - not OK (see screenshot_1.png)
![Screenshot_1](https://github.com/dEajL3kA/tee-win32/assets/48681366/3b663897-d1b2-4bc3-b2f0-d0b639ecb437)

example 2: CMD - not OK, TXT file - OK (see screenshot_2.png)
![Screenshot_2](https://github.com/dEajL3kA/tee-win32/assets/48681366/5bbb1a89-950a-4b97-9aa8-fbe65664d195)

I have tested both tee-x86 and tee-x64.

Can you recommend something? How can I fix this problem?

**Comment by dEajL3kA** [comment]
**Tee** is totally agnostic of character encodings! It just reads the output generated by the "source" (first) program from its `stdout` stream, in a byte-by-byte fashion, and then passes those bytes on to the `stdin` of the "destination" (second) program, or to the terminal window. Additionally, those bytes are dumped (copied) into the specified output file(s). But that is it 😏 

So, if you want the text to be encoded in a certain character encoding, e.g. UTF-8, then you **must** ensure that the "source" program actually writes the text to its `stdout` stream with the proper/desired character encoding! Again, please understand that **tee** just passes through the bytes that it receives from the "source" program in a "1:1" fashion. Also, be aware that **tee** has absolutely no control over how your terminal will interpret/display those bytes. The same holds true for your text editor!

BTW: I much recommend to use a text editor that properly deals with various character encodings, such as [**Notepad++**](https://notepad-plus-plus.org/downloads/) 😈 

Regards.

**Comment by dEajL3kA** [comment]
**Please check out this example:**
![tee-unicode](https://github.com/dEajL3kA/tee-win32/assets/13333150/54c865fd-f7a5-4f08-8fa5-2060e6988ac7)

**Comment by dEajL3kA** [comment]
I have added a Wiki page on this topic:
https://github.com/dEajL3kA/tee-win32/wiki/Character-Encodings

**Comment by victorsmart** [comment]
Hi!
Thank you so much for the quick response and solution of the problem! I changed the encoding before launching tee and everything worked out!
