### ISSUE TITLE
Correct display of the terminal

### ISSUE THREAD

**Issue by Lc4B** [dEajL3kA/tee-win32#3]
Could we have the "default" display of the terminal on output?
Let me explain better, if I launch a bat/cmd by passing it through tee, what tee shows in the terminal is not the normal display that the script would have (for example some commands are ignored or generate symbols for no reason, or another example are some ansi code that are not managed), I understand that in the output file these are only copied and I find them in code form, but why do I have an incorrect display in the terminal? it should just pass through tee without modification and yet there are things that are not recognized as before, can anything be done?
![goto-cls](https://github.com/dEajL3kA/tee-win32/assets/149880036/81c8c546-7c8e-4381-ba63-9c23c5111653)
![ansi](https://github.com/dEajL3kA/tee-win32/assets/149880036/72a811db-ea04-4aa6-aa56-bce6222d4dec)
Thank you

**Comment by dEajL3kA** [comment]
`tee-win32` is totally agnostic of character encodings, or terminal fonts, or whatever. It just pumps through the "raw" bytes that it receives from the ***source*** application and passes them on to the next process (e.g. terminal emulator) :smirk:

_...however_, the ***source*** application may detect that its `stdout` stream is **not** connected to a TTY (terminal) but is connected to a pipe – which is unavoidable when you put another process (e.g. "tee") in between the application and the terminal – and therefore change what it prints to the `stdout` stream! Indeed, some applications produce different output when they are connected to a TTY (terminal) vs. when they are connected to a pipe or file. But, of course, that is totally out of control of the _tee_ program.

**For more details and possible solutions, please see:**
https://github.com/dEajL3kA/tee-win32/wiki/Character-Encodings
